#!/usr/bin/env python3

from setuptools import setup, find_packages

setup(
    name="ddg-mcp",
    version="1.0.0",
    description="An awesome MCP generated by AI",
    author="AI Generator",
    packages=find_packages(),
    install_requires=[
        "httpx>=0.28.1",
        "fastmcp>=2.10.6",
        "pydantic>=2.0.0",

    ],
    entry_points={
        "console_scripts": [
            "ddg_mcp-mcp=ddg_mcp.app:main",
        ],
    },
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
)